Use hunspell dictionaries from the host filesystem.
ubuntu/thunderbird pull request #18
Opened 2024-09-19 08:08 UTC by nteodosio

Imitates Firefox' setup as in [1], ignoring compatibility stuff pertaining to the host-hunspell interface, which Thunderbird never had.

[1] https://github.com/canonical/firefox-snap/pull/53/

-------

### Verification

I had these hunspell dictionaries installed:

    hunspell-de-ch/oracular,now 20161207-12 all  [installiert]
    hunspell-en-us/oracular,now 1:2020.12.07-2 all  [installiert]

If I install the snap hereby produced, connect the interface and re-install it, I get in the `snap run --shell thunderbird`:

```
$ ls -la $SNAP_COMMON/snap-hunspell
total 8
drwxr-xr-x 2 root root 4096 Sep 19 09:55 .
drwxr-xr-x 4 root root 4096 Sep 19 09:53 ..
lrwxrwxrwx 1 root root   49 Sep 19 09:55 de_CH.aff -> /snap/thunderbird/x2/usr/share/hunspell/de_CH.aff
lrwxrwxrwx 1 root root   49 Sep 19 09:55 de_CH.dic -> /snap/thunderbird/x2/usr/share/hunspell/de_CH.dic
lrwxrwxrwx 1 root root   49 Sep 19 09:55 de_LI.aff -> /snap/thunderbird/x2/usr/share/hunspell/de_LI.aff
lrwxrwxrwx 1 root root   49 Sep 19 09:55 de_LI.dic -> /snap/thunderbird/x2/usr/share/hunspell/de_LI.dic
lrwxrwxrwx 1 root root   49 Sep 19 09:55 en_US.aff -> /snap/thunderbird/x2/usr/share/hunspell/en_US.aff
lrwxrwxrwx 1 root root   49 Sep 19 09:55 en_US.dic -> /snap/thunderbird/x2/usr/share/hunspell/en_US.dic
```

If I now do

    apt remove hunspell-en-us

and re-install the snap, I get

```
$ ls -la $SNAP_COMMON/snap-hunspell
total 8
drwxr-xr-x 2 root root 4096 Sep 19 09:56 .
drwxr-xr-x 4 root root 4096 Sep 19 09:53 ..
lrwxrwxrwx 1 root root   49 Sep 19 09:56 de_CH.aff -> /snap/thunderbird/x3/usr/share/hunspell/de_CH.aff
lrwxrwxrwx 1 root root   49 Sep 19 09:56 de_CH.dic -> /snap/thunderbird/x3/usr/share/hunspell/de_CH.dic
lrwxrwxrwx 1 root root   49 Sep 19 09:56 de_LI.aff -> /snap/thunderbird/x3/usr/share/hunspell/de_LI.aff
lrwxrwxrwx 1 root root   49 Sep 19 09:56 de_LI.dic -> /snap/thunderbird/x3/usr/share/hunspell/de_LI.dic
```

2024-09-19 09:40 UTC, seb128 requested changes
Thanks, that seems fine to be an is basically what we are already doing in Firefox. I've one nitpick about Firefox->Thunderbird in the script comments

2024-09-19 09:40 UTC, seb128 commented on snap/hooks/post-refresh
> +#   Firefox snap similarly to how they could for non-snap Firefox.
Firefox->Thunderbird

2024-09-19 09:47 UTC, nteodosio commented on snap/hooks/post-refresh
> +#   Firefox snap similarly to how they could for non-snap Firefox.
Thanks, fixed.

2024-09-19 09:50 UTC, seb128 approved these changes
Thanks. Seems fine to me but I will wait on Amin's review before merging

2024-09-26 10:41 UTC, bandali0 approved these changes
LGTM as well, thanks.

2024-09-26 10:53 UTC, merged