snap: fixes desktop file that'll attached to the window
ubuntu/thunderbird pull request #26
Opened 2024-11-20 13:55 UTC by soumyaDghosh

Similar to https://github.com/canonical/firefox-snap/pull/74

2024-11-20 17:08 UTC, aleasto commented
Makes sense to me!

2024-11-20 17:34 UTC, aleasto commented on snapcraft.yaml
> +title: Thunderbird
This seems unrelated

2024-11-20 17:56 UTC, soumyaDghosh commented on snapcraft.yaml
> +title: Thunderbird
This adds some metadata... Which I think firefox should've it too

2024-11-20 22:49 UTC, hellsworth commented
looks great and thanks for fixing this!

2024-11-21 08:05 UTC, seb128 requested changes
It might make sense to add a title but that isn't related to fixing the bug described there and not what the commit message describe so please revert that part and submit another commit/PR for it with rational if you want to see that landed

2024-11-21 08:14 UTC, soumyaDghosh commented
> It might make sense to add a title but that isn't related to fixing the bug described there and not what the commit message describe so please revert that part and submit another commit/PR for it with rational if you want to see that landed

Sure... Thanks!

2024-11-26 06:58 UTC, soumyaDghosh commented
Sorry @seb128 I forgot about this PR

2024-11-26 12:05 UTC, seb128 approved these changes
Thanks

2024-11-26 12:05 UTC, merged